parser: babel-eslint
extends: airbnb
env:
  browser: true
  node: true
  mocha: true
rules:
  strict: 0
  no-console: 0
  max-len: off
  camelcase: off
  no-use-before-define: 0
  arrow-parens: ["error", "as-needed"]
  no-mixed-operators: 0
  no-await-in-loop: off
  import/prefer-default-export: off
